/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameUI from "./script/GameUI"
import Game from "./script/Game"
import SetDialog from "./script/SetDialog"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1024;
    static height:number=648;
    static scaleMode:string="fixedwidth";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="ui/mian_scene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/GameUI.ts",GameUI);
        reg("script/Game.ts",Game);
        reg("script/SetDialog.ts",SetDialog);
    }
}
GameConfig.init();