/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.ui {
    export class mian_sceneUI extends Scene {
		public pause_label:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("ui/mian_scene");
        }
    }
    REG("ui.ui.mian_sceneUI",mian_sceneUI);
    export class set_dialogUI extends Dialog {
		public resume_label:laya.display.Text;
		public pause_label:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("ui/set_dialog");
        }
    }
    REG("ui.ui.set_dialogUI",set_dialogUI);
}